### ISSUE TITLE
Does not support 60fps frame by frame

### ISSUE THREAD

**Issue by Tagette** [CalumJEadie/frame-by-frame#14]
I need to view videos at the most detailed frame by frame as I can. I would download the video if it was legal and if I had a better internet connection. This plugin makes everything easier however since you tube now has 60 fps it would be nice to be able to iterate through each frame at 60 fps.

**Comment by regularWand** [comment]
Hi Tagette,

Thanks for your feedback. I actually have an experimental branch of `frame-by-frame` which supports 60 fps (`O` key to toggle), screenshotting (apostrophe or `'` key to trigger and `shift + '` to download), and faster forward seek. You can download this version here: https://github.com/regularWand/frame-by-frame. In your Chrome extension settings you must enable developer mode and hit `load unpacked extension` and point to where you have downloaded `frame-by-frame`.

I know this reply is rather late, but that is because I am a student and am not in a field at all related to programming. I have recently picked up programming again and hope to update the official extension with more features in the future!

**Comment by regularWand** [comment]
Hi again, I was playing around with 'frame-by-frame' and thought I was experiencing a bug, but it seems Google have recently implemented frame skipping on Youtube by default using the angled bracket keys `<` and `>`.  It is adaptive with the frame rate of the video (including 60 fps), but is not as flexible as `frame-by-frame` and is a rather limited feature. It also uses a rather slow seeking technique which I have experimentally improved upon (only for forward seeking).
